---
# yaml-language-server: $schema=https://schemas.tholinka.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: volsync
spec:
  groups:
    - name: volsync.rules
      rules:
        - alert: VolSyncComponentAbsent
          expr: |
            absent(up{job="volsync-metrics"})
          annotations:
            summary: >
              VolSync component has disappeared from Prometheus target discovery
          for: 5m
          labels:
            severity: critical

        - alert: VolSyncVolumeOutOfSync
          expr: |
            volsync_volume_out_of_sync == 1
          annotations:
            summary: >
              {{ $labels.obj_namespace }}/{{ $labels.obj_name }} volume is out of sync
          for: 5m
          labels:
            severity: critical

        - alert: VolSyncNoSyncInLastSixHours
          expr: |
            (time() - volsync_sync_duration_seconds_count) > 21600
            and
            volsync_missed_intervals_total > 0
          annotations:
            summary: >
              {{ $labels.obj_namespace }}/{{ $labels.obj_name }} has not synced in over 6 hours
          for: 10m
          labels:
            severity: warning

        - alert: VolSyncMissedIntervals
          expr: |
            increase(volsync_missed_intervals_total[6h]) > 2
          annotations:
            summary: >
              {{ $labels.obj_namespace }}/{{ $labels.obj_name }} has missed multiple sync intervals
          for: 5m
          labels:
            severity: warning
