apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secret
stringData:
    ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:xTx/9r2ZRhjQvGo=,iv:6blfmqBN137bntk7CZTxsAMF/TgYJiGFK7qQTRCjmbE=,tag:UgWTD6HNjJd4bbLy9JQZjA==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:ywK0ZoBKz9F3Xio=,iv:gnGzogPWUNYi194Qhxwy8tLkI1SfwOtV6PHcqMb/kZ0=,tag:yZurFz8Hf/zp/F3GkHGCFg==,type:str]
    HEALTHCHECKS_IO_HEARTBEAT_URL: ENC[AES256_GCM,data:mg05P/xms7bAZcQ=,iv:tG8/r5tSAdM+V9SmWpb4kq0zMI3zPSMsUizX/oMMOBE=,tag:BKNx0Ox2Bl7akkBs7RFC/g==,type:str]
sops:
    age:
        - recipient: age1dgn20j20q0ck5xkw3kugyur2ygkdkga740x8e7qz6jsktc9fag0qthmpsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaXNRNjRJZ3k0MVMwbjFm
            eXlLUzFQeFZjK0llcVVZdWpBbCtET0cxY0RrClhtUzBRSE5pdnZhcnk5MW8yQnlx
            VHR5b1FNSy9wNFlWWHJ2azNOS0pMSzAKLS0tIDhpQ2dHSDdiWXdhOXl3SGFuOEVV
            VnhDazE4Q0VCSXk2NTNsN2xrOHB5MGMK6vCXo5nVmFVE6rUns6CTgxyRY2zhejd/
            U6pxu16j1fDeZdU8MHR8+lDTK1ExjqoSbMTWfrkaEpOE8SSBpMdcLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:44:39Z"
    mac: ENC[AES256_GCM,data:Oz5/p23CLhXyS2a1hzCrV5FJ+ycuZ+kyxlbNh+MPBKaP7lH4qUSlZkZ30WtscosQRrDE7PXUzlpdNcsTxTs9zzkwn85UFFuz9fVJji7gse8sDx9/0+b7XV7kEFONwQ08iO0j6CtebvEFreGTXxCaIho8ighomwrtBHGzG3TDUzY=,iv:ZO0bMhTvzwYdomxKpzrVrLfgGAW9wrcUyAXCTyFsl8A=,tag:9APTLvIbZ3SjONgKdDAOrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
