---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-mariadb
stringData:
  host: ${MARIADB_INSTANCE:=mariadb}.database.svc.cluster.local
  port: "3306"
  database: ${APP}
  username: ${DATABASE_OWNER:=${APP}}
  # Connection URL for apps that accept a DSN
  url: 'mysql://${DATABASE_OWNER:=${APP}}@${MARIADB_INSTANCE:=mariadb}.database.svc.cluster.local:3306/${APP}'
