---
# yaml-language-server: $schema=https://schemas.tholinka.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prometheus-adapter
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    prometheus:
      url: http://vmsingle-victoria-metrics.observability.svc.cluster.local
      port: 8428
    rules:
      default: false
