---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: ${APP}
spec:
  mariaDbRef:
    name: ${MARIADB_INSTANCE}
  # Password managed via the operator's generated secret
  passwordSecretKeyRef:
    name: ${APP}-mariadb-password
    key: password
    generate: true
  host: "%"
  cleanupPolicy: Skip
  requeueInterval: 30s
  retryInterval: 5s
