apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:kq9xffruH+YqaMioAHQ92KZRPthlAbhujwmwIdhJSjb3J9K6oC2ACA==,iv:6y0YTlPd838YPXcjaa9DUQHfD74lwGb7l9sCM5eJMAc=,tag:NB0RagqFpO7sq7wnPh4Sjw==,type:str]
sops:
  age:
    - recipient: age1dgn20j20q0ck5xkw3kugyur2ygkdkga740x8e7qz6jsktc9fag0qthmpsg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaXNRNjRJZ3k0MVMwbjFm
        eXlLUzFQeFZjK0llcVVZdWpBbCtET0cxY0RrClhtUzBRSE5pdnZhcnk5MW8yQnlx
        VHR5b1FNSy9wNFlWWHJ2azNOS0pMSzAKLS0tIDhpQ2dHSDdiWXdhOXl3SGFuOEVV
        VnhDazE4Q0VCSXk2NTNsN2xrOHB5MGMK6vCXo5nVmFVE6rUns6CTgxyRY2zhejd/
        U6pxu16j1fDeZdU8MHR8+lDTK1ExjqoSbMTWfrkaEpOE8SSBpMdcLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T08:19:53Z"
  mac: ENC[AES256_GCM,data:nR7BrTB7daZ8UcTWERHxBPH2eF0Kaj8WG3F+qP+BcrkMH3g59tW+5CGY2crXTGSylGbBhrPiA5jA0pbSTIkZXOBs1aBQ2557bK0EgYKFh4G+sHRnXGh16k/DcBArN54bwFbGvCpRE7+KhLzpuQl1p2p1KuvFhPNy9KQnFwtmAeA=,iv:7xNkkKreSL6O2YnGvw/Lsu1J3dYLldcYY/VW6Ch4x+E=,tag:FGzCMLBuLd/v4OHhU6tFbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
