apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:f81E5oe7Bsd4Xp2q,iv:vjTEoLzjmckoSiU+K9HOkzTl6uhCtTk5yKvfCfSr/6I=,tag:R2q1q+7PjkslOA5/TzrraA==,type:str]
sops:
  age:
    - recipient: age1dgn20j20q0ck5xkw3kugyur2ygkdkga740x8e7qz6jsktc9fag0qthmpsg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZFlVWnBNdU5lN3VTMGFC
        Wk51Mnk5RHYySGRySjJTZ1NTWXo4czduOGp3ClkyTEt4ZlVWMmlqWGhxUW5mblM5
        WnZ0cmtnWmowZHl2ZitMNUxSYjMxQ2cKLS0tIGs1NUlIMkRBWDlJK09haE1VSmJz
        MUZ6QVZIVzA4NFBwRzlqYlFDRGwwTm8K6awbrjqIgI5P1Te4o+ioMHZsew0ROti2
        L2u+6rdm/ZxYLOufj+6Yr/Ga71f7vk88DvwAyzfpwgWWNmds+KOiBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T08:19:53Z"
  mac: ENC[AES256_GCM,data:FXEDb9EE9oYZlA9VcNmvRlLBOU6IqJ2WDijId7CT5b1sfMUnNxE3JwWyXASA5B6tL3EPBIWrx5dZNNAXnbEUg5lE33bgR6ZkNO+Jy2EpNatn91MRbaIznxZE94JNOmUx+i46uH25c5Bz8vRwvVkGU+xktrzuwb3G0SN+EQRvaEc=,iv:6WEgo22fsoqpcZDTdG2yVC9/nIUcNmNRY5iHJH/EUUM=,tag:q6PFEvobPAov6w465RDm5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
