---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret sure-am
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *secret
    template:
      data:
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
        OPENAI_ACCESS_TOKEN: "{{ .OPENAI_ACCESS_TOKEN }}"
        OIDC_AUTHENTIK_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_AUTHENTIK_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: *secret
