apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:kUiUU2PSktndC9xEnij4Ul6Eb5SM4ybd+DBAaXRSe5Q=,iv:/eQWNmtoKKRYklJ/G3rIQb1018+WPiM5XQTJyWS0yys=,tag:T5LG+ktoEdXk7Bx526QIhw==,type:str]
sops:
  age:
    - recipient: age1dgn20j20q0ck5xkw3kugyur2ygkdkga740x8e7qz6jsktc9fag0qthmpsg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveW1ra08xck41VFNQaGpS
        Q0pYdDZLTjBQUGF6VzJBdkhKRzBoa2Y2V2w0ClpBelY2UVI5Uk5KZmRQVDdoQ3dM
        UXRzYmhab2MxTHh2RE91YU4xcGtBVGMKLS0tIEVWb1VCN1JwVS9SWC83ZGxlcGli
        RmRmZHFyQ2Raa3cvTlIyR0VwaGhKejAKRf3qI4hSmK5xsqlKpoqyVJxQciUzLV3Y
        4kiGGhMJUus92LN7PO9RHi6SWP0hvrea50RXwA8Q0kL3xACNMLei/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T08:19:53Z"
  mac: ENC[AES256_GCM,data:5TtdJ2QWHsj9VEMJJIj1xFzmiekvgovzBkqufq1/nUgAL4FBR2ED2JEh3Kqj9iYeHJfTgZ10HV5kqb39QVQjo6RaWTei0m7quc25S151cfXQJOQyUbi+2QrBQYqlmy2wdtls6+u0DeYu23nZ1UL1GcN4QeR+vLq3iOK9UUjskJE=,iv:o9ZbxhmP14yIGMefz9hKxTwd904zXp1YF0pLDoIDn1c=,tag:WIh/sqOqf3v6FyJUthyxlA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
