---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: grimmory-secret
    template:
      data:
        MARIADB_ROOT_PASSWORD: '{{ .MYSQL_ROOT_PASSWORD_ }}'
        MARIADB_PASSWORD: '{{ .DB_PASSWORD_ }}'
        DATABASE_PASSWORD: '{{ .DB_PASSWORD_ }}'
        DATABASE_USERNAME: '{{ .DB_USER_ }}'
  dataFrom:
    - extract:
        key: grimmory
