apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    #ENC[AES256_GCM,data:55Y7rD/72u5E9PY=,iv:O578wAdC1ij6hplZDh2BTkFOxI+KrgGbRfNCs91t6Wk=,tag:tWAjubtV2TWQvCphxVwh5w==,type:comment]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:3C47OO6ziL8imUpV7i//rQHknExmfR1UwVxqE1064Fz58ld0ZOI=,iv:Z8R6E7VzT60rKxBq40UtwFNVksPTWnQfO0tylGQP90Y=,tag:PlEeBZkQaPBxGGw+BJ0eFA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ID25m84/SCBNsOU=,iv:bK2eBLmyUbh4tqciYRoGSU+ANPD+Et5xD2pWfyEt858=,tag:AhacgCQZcnsneho27WmalA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:dzQHVFJ/gr6vDL4=,iv:+jUuhDcy/VmosMJ7vyuXzuHYbwHn/9s5VmFJzUpxbVM=,tag:OPu0r7mSBn8kylRUrmyMXw==,type:str]
sops:
    age:
        - recipient: age1dgn20j20q0ck5xkw3kugyur2ygkdkga740x8e7qz6jsktc9fag0qthmpsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaXNRNjRJZ3k0MVMwbjFm
            eXlLUzFQeFZjK0llcVVZdWpBbCtET0cxY0RrClhtUzBRSE5pdnZhcnk5MW8yQnlx
            VHR5b1FNSy9wNFlWWHJ2azNOS0pMSzAKLS0tIDhpQ2dHSDdiWXdhOXl3SGFuOEVV
            VnhDazE4Q0VCSXk2NTNsN2xrOHB5MGMK6vCXo5nVmFVE6rUns6CTgxyRY2zhejd/
            U6pxu16j1fDeZdU8MHR8+lDTK1ExjqoSbMTWfrkaEpOE8SSBpMdcLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:43:18Z"
    mac: ENC[AES256_GCM,data:21xlxZpRAEyEPXm0snpwq9U/7wnzTqWdlARrULSppV7mqnjz/xRoP+qh3Kvug06NEWWqrOxQtHmx73tth5o57rbMV76hUPWnSliTsjNi/lbc5DPntL4tzfN07c+VF3oa6CzXJnXjX90pft9L2zZ3NEoquF4eYK4iWgWxH2dtL+Y=,iv:zZXho7YkSDhMXRv79WNGIw7cUXCbelBRb6CvQytOyOs=,tag:PwqsrP0YQWAFCJc4J6Ogcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
