apiVersion: v1
kind: Secret
metadata:
    name: bitwarden
    namespace: security
type: Opaque
stringData:
    BITWARDEN_MACHINE_KEY: ENC[AES256_GCM,data:jfGv0UnPks8aSbZXIZ8d3RfbQ9UAsvH9BD1Wklf8MMTLAVSeUEmwa7LYCuNRajQyB0mO/Fwwe0YXqRgfy/spkib2lo7tgLzdW+aJYtnQ1pA35JEWLvI0qk8m9gERyQ==,iv:jtmt8guJpq5CaKk7hjLkjgJNV/0EkeF89qRv2b2Q1wc=,tag:cLKnRbZeS+yHvnWN63Tydg==,type:str]
    BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:9Gnq2oo99fKdDEO41rpNEBoHEx8uyi992FGfLgQLnuP0g2fb,iv:0+RK46xi1cQFQ9mR7s8Pvmax8VinrmJ1zi8vgkLOsyY=,tag:gMU5eJE5wORltOncuZPuMQ==,type:str]
    BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:5KW6N8HbKhQH7wREX2tPPoC5jWcgjWcXgCLjQULDL2DC6dsz,iv:jbDuPlGKEqS5Fnl4xDJRjmmxkqinqBY543JWQY/AKoQ=,tag:q5TSI2/C6PWc2GaliynWpg==,type:str]
sops:
    age:
        - recipient: age1dgn20j20q0ck5xkw3kugyur2ygkdkga740x8e7qz6jsktc9fag0qthmpsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaXNRNjRJZ3k0MVMwbjFm
            eXlLUzFQeFZjK0llcVVZdWpBbCtET0cxY0RrClhtUzBRSE5pdnZhcnk5MW8yQnlx
            VHR5b1FNSy9wNFlWWHJ2azNOS0pMSzAKLS0tIDhpQ2dHSDdiWXdhOXl3SGFuOEVV
            VnhDazE4Q0VCSXk2NTNsN2xrOHB5MGMK6vCXo5nVmFVE6rUns6CTgxyRY2zhejd/
            U6pxu16j1fDeZdU8MHR8+lDTK1ExjqoSbMTWfrkaEpOE8SSBpMdcLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:35:59Z"
    mac: ENC[AES256_GCM,data:btuMkxeE3kgZ4PZ9cWbTS5asPeFsLoRXc/MCMCfHG0oeh04UNI0xL/f3WjNkLGd3uNrmCJiJudfC4/yCYy6He8fcGWv3PZkXrwzGwRnz4uBcCjHyrdPO3s7B0Vzt5cWhrgtuH5h7QoxaDETxJ6SVcXDI6vZDUofOE0sNEeOfmqg=,iv:uGqvzjub5J3ls+eCOucCaydr7RxuDXa1jI6JSNwgNJY=,tag:bq2wzEc0hs9gm7I6EWpc/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
