---
# - Home:
#     - Home Assistant:
#         href: https://ha.laurivan.com
#         icon: home-assistant.png
#         #description: Home Assistant
#         app: home-assistant
#         namespace: home-automation
#         widget:
#           type: homeassistant
#           url: http://home-assistant.home-automation.svc.cluster.local.:8123
#           key: '{{HOMEPAGE_VAR_HA_TOKEN}}'
#           custom:
#             # yamllint disable-line rule:quoted-strings
#             - template: "{{ states.person|selectattr('state','equalto','home')|list|length }} / {{ states.person|list|length }}"
#               label: homeassistant.people_home
#             # yamllint disable-line rule:quoted-strings
#             - template: "{{ states.light|selectattr('state','equalto','on')|list|length }} / {{ states.light|list|length }}"
#               label: homeassistant.lights_on

- Media:
    - Autobrr:
        icon: autobrr.svg
        href: https://autobrr.laurivan.com
        #description: Download Automation
        app: autobrr
        namespace: downloads
        widget:
          type: autobrr
          url: http://autobrr.downloads.svc.cluster.local.:80
          key: '{{HOMEPAGE_VAR_AUTOBRR_TOKEN}}'
    # - Bazarr:
    #     icon: bazarr.svg
    #     href: https://bazarr.laurivan.com
    #     #description: Subtitles Management
    #     app: bazarr
    #     namespace: downloads
    #     widget:
    #       type: bazarr
    #       url: http://bazarr.downloads.svc.cluster.local:6767
    #       key: '{{HOMEPAGE_VAR_BAZARR_TOKEN}}'
    # - Kavita:
    #     href: https://kavita.laurivan.com
    #     icon: kavita.svg
    #     app: kavita
    #     namespace: media
    #     widget:
    #       type: kavita
    #       url: http://kavita.media.svc.cluster.local.:5000
    #       key: '{{HOMEPAGE_VAR_KAVITA_TOKEN}}'
    # - Lidarr:
    #     href: https://lidarr.laurivan.com
    #     icon: lidarr.svg
    #     app: lidarr
    #     namespace: downloads
    #     widget:
    #       type: lidarr
    #       url: http://lidarr.downloads.svc.cluster.local
    #       key: '{{HOMEPAGE_VAR_LIDARR_TOKEN}}'
    # - Plex:
    #     icon: plex.svg
    #     href: https://plex.laurivan.com
    #     #description: Media Server
    #     app: plex
    #     namespace: media
    #     widget:
    #       type: plex
    #       url: http://plex.media.svc.cluster.local.:32400
    #       key: '{{HOMEPAGE_VAR_PLEX_TOKEN}}'
    #       enableNowPlaying: true
    - Prowlarr:
        icon: prowlarr.svg
        href: https://prowlarr.laurivan.com
        app: prowlarr
        namespace: downloads
        widget:
          type: prowlarr
          url: http://prowlarr.downloads.svc.cluster.local.:80
          key: '{{HOMEPAGE_VAR_PROWLARR_TOKEN}}'
    - qBittorrent:
        icon: qbittorrent.svg
        href: https://qb.laurivan.com
        app: qbittorrent
        namespace: downloads
        widget:
          type: qbittorrent
          url: '{{HOMEPAGE_VAR_QBITTORRENT_PROXY}}'
          enableLeechProgress: true # optional, defaults to false
    - qui:
        icon: qui.svg
        href: https://qui.laurivan.com
        app: qui
        namespace: downloads
    - Radarr:
        href: https://radarr.laurivan.com
        icon: radarr.svg
        #description: Movies
        app: radarr
        namespace: downloads
        widget:
          type: radarr
          url: http://radarr.downloads.svc.cluster.local.:80
          key: '{{HOMEPAGE_VAR_RADARR_TOKEN}}'
    # - SABnzbd:
    #     icon: sabnzbd.svg
    #     href: https://sab.laurivan.com
    #     app: sabnzbd
    #     namespace: downloads
    #     widget:
    #       type: sabnzbd
    #       url: http://sabnzbd.downloads.svc.cluster.local.:80
    #       key: '{{HOMEPAGE_VAR_SABNZBD_TOKEN}}'
    - Seerr:
        icon: jellyseerr.svg
        href: https://requests.laurivan.com
        app: seerr
        namespace: downloads
        widget:
          type: jellyseerr
          url: http://seerr.downloads.svc.cluster.local.:80
          key: '{{HOMEPAGE_VAR_SEERR_TOKEN}}'
    # - slskd:
    #     href: https://slskd.laurivan.com
    #     icon: slskd.svg
    #     app: slskd
    #     namespace: media
    #     widget:
    #       type: slskd
    #       url: http://slskd.media.svc.cluster.local:80
    #       key: '{{HOMEPAGE_VAR_SLSKD_TOKEN}}'
    - Sonarr:
        href: https://sonarr.laurivan.com
        icon: sonarr.svg
        #description: TV Shows
        app: sonarr
        namespace: downloads
        widget:
          type: sonarr
          url: http://sonarr.downloads.svc.cluster.local.:80
          key: '{{HOMEPAGE_VAR_SONARR_TOKEN}}'
    # - Tautulli:
    #     icon: tautulli.svg
    #     href: https://tautulli.laurivan.com
    #     app: plex
    #     namespace: media
    #     widget:
    #       type: tautulli
    #       url: http://tautulli.media.svc.cluster.local.:80
    #       key: '{{HOMEPAGE_VAR_TAUTULLI_TOKEN}}'
    #       enableNowPlaying: true
    ### no widgets at bottom of list
    # - Shelfmark:
    #     href: https://shelfmark.laurivan.com
    #     icon: calibre.svg
    #     app: shelfmark
    #     namespace: media
    # - Maintainerr:
    #     href: https://maintainerr.laurivan.com
    #     icon: maintainerr.svg
    #     app: maintainerr
    #     namespace: downloads
    # - Upload-Assistant:
    #     href: https://upload-assistant.laurivan.com
    #     icon: mdi-upload
    #     app: upload-assistant
    #     namespace: downloads

# - Infrastructure:
#     - Unifi:
#         icon: unifi.svg
#         href: https://router.internal
#         #description: Unifi Network Application
#         namespace: network

- Calendar:
    - Agenda:
        widget:
          type: calendar
          view: agenda # optional - possible values monthly, agenda
          maxEvents: 5 # optional - defaults to 10
          integrations: # optional
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Media # group name where widget exists
              service_name: Sonarr # service name for that widget
            - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Media # group name where widget exists
              service_name: Radarr # service name for that widget
