apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:QgMfJKKeMSxL8YXCYaHsog533Qfb1U08rsgr1Tz580TqyyNEQvW1nbZAXGSc7UZQZFRPXYHFN47hPLB84KR/2Sgiw2GCqtgaB7d73yWUQmZ2x3op0eJHJ5hMfts3sTV9NgRstviQPvvRtRmyhRA74XsPuznosFTvgy6AmkPlSkiz8dvkOhndlhtZ0klsHW4S/kOQoq9K/XtUkSeGNzgfZGVi2p+E7N+QQ47l1E45tm8N6ZZm,iv:dnoHjoEG6eQLVOI2nT2dxL2l5gwLaNNcKQLhAY4IGok=,tag:P5X7MyTH8Tt9uZzTIvhTZQ==,type:str]
sops:
  age:
    - recipient: age1dgn20j20q0ck5xkw3kugyur2ygkdkga740x8e7qz6jsktc9fag0qthmpsg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzc1h2L1ZGUkR6Ti95VTUv
        RFBLZFhsT1lkYm5SSUZrUEdxOFZtYi82Z0VNCjdYOE10ZGVjV0JjTy9ha3NrMldP
        MCtMQndSc3Z6a0FyQW9ScHpSdnNzQkEKLS0tIDdpcHk0UG9SZnRFYzdESnNpOVVR
        ZHBmbzROYXhFdkJ1TDhFand4Z0hHV1kKQL+LaRVbeFzLNF1XC5SFsp+pAf2aRu1E
        H77EkonnRHoLtwlGVd8FuYXZvmvmvtPfU8GSlqONyzMbWwUxTxjr7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T08:19:53Z"
  mac: ENC[AES256_GCM,data:QmFVjadU+wDagvV3tRsE+JvydwgC7ZcoPG2oVrO5ljHjOBnM0hZanwFXowjy//461M3zGld0UJ8t1vp4KReNyEfj/QlhCBi+zgY0A7712Y14FzcmT1psVwJoBTrLnbp2ThcD02yvQv4wiYyrRV4fNOsLYyiOxH4BuwjivFHmb8M=,iv:ndVcVGg8TmBIONLTz0xcUoqM/2nsawhlAZ6X6K2VbQQ=,tag:TdytkzqEozOYlfABRm2i8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
