---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-backup-secret
  namespace: &namespace database
spec:
  interval: 1h
  path: ./kubernetes/apps/database/mariadb-operator/backup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: mariadb-backup
      namespace: *namespace
