---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cnpg-crds.ks.yaml
  - ./cnpg.ks.yaml
  - ./postgres-cluster.ks.yaml
  - ./plugin-barman-cloud.ks.yaml
  - ./pgadmin.ks.yaml