---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        signing_private_key: "{{ .FORGEJO_SIGNING_PRIVATE_KEY }}"
        signing_public_key: "{{ .FORGEJO_SIGNING_PUBLIC_KEY }}"
  dataFrom:
    - extract:
        key: *name
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: forgejo-oidc
    creationPolicy: Owner
    template:
      data:
        key: "{{ .FORGEJO_OIDC_CLIENT_ID }}"
        secret: "{{ .FORGEJO_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: forgejo
