apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:zT+JT4XxZfhT6S4m88/ia4d9HbdghcbwhF90yL7xe8S8LJUtaZzJww==,iv:l0wQf5gzcJ31d/clAizltsjMh+abXk16/xIjmBmJbug=,tag:d0UAszzSV7uSH1PudYEKzA==,type:str]
sops:
  age:
    - recipient: age1dgn20j20q0ck5xkw3kugyur2ygkdkga740x8e7qz6jsktc9fag0qthmpsg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdXBBbXNXcFJnbWsxOTdL
        eTJaeTh0MHQrd29JOFNEZzFoV2haOWVRYm5ZClVtN0VNU0pBNkRRTGdPYU9FODF4
        UUNlbmVaeUVIY3NzZThkVmR0Ym53ZlUKLS0tIHA3OEhoVkRoQXpiWEdXcFRmRmxy
        VlllMFovMWMvM3FBaGREcGxYOW93cmcKeWeiyDLfnLdyH6Z0iTkbOSMW0YgX9qfz
        86y24H7Qdahzkpc/yjA+eCe3XLlBP+QeJ0O82oZKsVopyK/zKMXmVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T08:19:53Z"
  mac: ENC[AES256_GCM,data:chnF3XlN01B63aMCoqaOvVWCPBrs15J4GfkeIoviv7k+0QB+nfT5TpR3VyIxRzyN3e8KotYgRIghvNX9vz8fj0AszMEYNlbauo64JYWNQEMsSy30uQjr7IH9Y5VYd2stq5+4+uP62WG4hnnBHr/L43Dn6EhwxESov5bFoDu34dE=,iv:G0epI/3oYS7EqQPBpNGarXj5j/ETio9B6X1Wffw8YWA=,tag:jD8/HtY8HAfCw5ynhmSWsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
