---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/common
resources:
  - ./grafana
  # - ./kube-prometheus-stack
  - ./prometheus-adapter
  - ./prometheus-operator-crds
  # - ./keda
  - ./victoria-metrics
  - ./victoria-logs
  - ./node-exporter
  - ./silence-operator
  - ./smartctl-exporter
  # - ./unpoller - enable vack when we have the unifi controller set up.
  # Disable headlamp because it's installed as a desktop app
  # - ./gitops
