---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: true

  image: docker.io/library/mariadb:11.8

  port: 3306

  storage:
    size: 5Gi
    storageClassName: openebs-hostpath

  # Single instance for homelab
  replicas: 1

  # Burstable QoS
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=256M
    max_allowed_packet=256M
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci

  nodeSelector:
    node.kubernetes.io/ssd: ""

  metrics:
    enabled: true
