apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
stringData:
    api-token: ENC[AES256_GCM,data:lNV2t8rWZzPzKU6X99IlhCNqYOH4vzG/Lw==,iv:IozI8BpQoKYs91O4NxjnRWmLNl8FSMwbDnqkZJXGEaA=,tag:InE6hCrOMy429YDOIOWUfg==,type:str]
    password: ENC[AES256_GCM,data:1jL44x2cyY7ezYeUWaPhXyf72BbJFy8aYg==,iv:dwU9Ssk4WihLT6HkGb5f0CElLpeNePmX8xWRmoOx8PE=,tag:UJIhIw9piHLA6CPyC9HuWw==,type:str]
sops:
    age:
        - recipient: age1dgn20j20q0ck5xkw3kugyur2ygkdkga740x8e7qz6jsktc9fag0qthmpsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaXNRNjRJZ3k0MVMwbjFm
            eXlLUzFQeFZjK0llcVVZdWpBbCtET0cxY0RrClhtUzBRSE5pdnZhcnk5MW8yQnlx
            VHR5b1FNSy9wNFlWWHJ2azNOS0pMSzAKLS0tIDhpQ2dHSDdiWXdhOXl3SGFuOEVV
            VnhDazE4Q0VCSXk2NTNsN2xrOHB5MGMK6vCXo5nVmFVE6rUns6CTgxyRY2zhejd/
            U6pxu16j1fDeZdU8MHR8+lDTK1ExjqoSbMTWfrkaEpOE8SSBpMdcLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T21:32:49Z"
    mac: ENC[AES256_GCM,data:Ewq2/MK1sIVnjMzlWwgg8xJhKw/gPCNJEhOiSge0+Tvz3StHw2KTI9/fOOYLG93VhpgCAY630ySe7di01PslEq8gEoELD/Z7Hp5QWWiQE6gC2kwQDnN6xHjjQSjuRhrlnrPtd481QitDEFBhmoUOL2KFb/KjIP6fJeNje1NGQek=,iv:wJsfl1rMlFN/8XwfDJ58Bn2m1Neb7cfsvWjW/mMPbRE=,tag:0aItilH3bmCvIVTCdQOJsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
