# host-record matches host names with IP addresses
# host-record syntax:
# host-record=<name>[,<name>],<ipv4>[,<ipv4>][,<ipv6>[,<ipv6]]


host-record=localhost,127.0.0.1,::1 # NFS mounts VERY slow sometimes on the NAS without this, must be waiting for a timeout of some kind?

# Tholinka examples:
# host-record=pon.internal,192.168.11.1
# host-record=cluster.servers.internal,192.168.21.2,fd83:43a4:6dab:21::2
# host-record=unifi,192.168.20.1,192.168.5.1,192.168.30.1
# host-record=dns,pihole,192.168.21.6,192.168.20.100,fd83:43a4:6dab:21::6
# host-record=plex.servers.internal,192.168.21.30,fd83:43a4:6dab:21::30
