---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard. It provides
      a simple way to get insights into your GitOps workloads.
  name: ww-gitops
spec:
  chartRef:
    kind: OCIRepository
    name: ww-gitops
  interval: 1h
  values:
    adminUser:
      create: true
      passwordHash: $2a$10$Zniz720/riX77oAjg.jU2OJ7hHm5tQjyMo15CgS9ne.nGgk7eoSqu
      username: admin
