---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  chartRef:
    kind: OCIRepository
    name: headlamp
  interval: 1h
  values:
    config:
      watchPlugins: true
    pluginsManager:
      enabled: true
      configContent: |
        plugins:
          - name: flux
            source: https://artifacthub.io/packages/headlamp/headlamp-flux/flux
            version: 0.1.1
        installOptions:
          parallel: true
